export const data = [
  {
    id: 1,
    score: 45,
    reward: 5,
    approximateTime: 5,
    bgColor: "bg-[#D8EBFF]",
    taskTitle: "Complete your profile",
  },
  {
    id: 1,
    score: 55,
    reward: 7,
    approximateTime: 8,
    bgColor: "bg-[#FFE9E7]",
    taskTitle: "Verify your identity",
  },
  {
    id: 3,
    score: 15,
    reward: 5,
    approximateTime: 8,
    bgColor: "bg-white",
    taskTitle: "Employment Task",
    ratings: 675,
    ratingsLevel: "/images/ratings.svg",
  },
  {
    id: 4,
    score: 15,
    reward: 5,
    approximateTime: 8,
    bgColor: "bg-white",
    taskTitle: "Lifestyle Task",
    ratings: 675,
    ratingsLevel: "/images/ratings.svg",
  },
  {
    id: 5,
    score: 15,
    reward: 5,
    approximateTime: 8,
    bgColor: "bg-white",
    taskTitle: "Health Task",
    ratings: 675,
    ratingsLevel: "/images/ratings.svg",
  },
];
