export const verifyPhoneTask = {
  id: "verify-phone",
  href: "/dashboard/questionnaire/verify-phone",
  score: 55,
  reward: 5,
  approximateTime: 8,
  bgColor: "bg-[#FFE9E7]",
  taskTitle: "Verify phone number",
  priority: true,
  completed: true,
  icon: "/images/group.png",
};

export const completeProfileTask = {
  id: "complete-profile",
  href: "/dashboard/questionnaire/complete-profile",
  score: 45,
  reward: 5,
  approximateTime: 5,
  bgColor: "bg-[#D8EBFF]",
  taskTitle: "Complete profile",
  priority: true,
  completed: true,
  icon: "/images/complete-profile.png",
};

export const priorityTask = [
  // {
  //   id: "verify-identity",
  //   href: "#",
  //   score: 55,
  //   reward: 7,
  //   approximateTime: 8,
  //   bgColor: "bg-[#FFE9E7]",
  //   taskTitle: "Verify your identity",
  //   priority: true,
  //   completed: true,
  //   icon: "/images/group.png",
  // },
] as any[];

export const todo = [
  {
    id: "environment-task",
    score: 15,
    reward: 5,
    approximateTime: 8,
    bgColor: "bg-white",
    taskTitle: "Environment Task",
    ratings: 675,
    ratingsLevel: "/images/ratings.svg",
    completed: false,
  },
  {
    id: "emplyment-task",
    score: 15,
    reward: 5,
    approximateTime: 8,
    bgColor: "bg-white",
    taskTitle: "Employment Task",
    ratings: 675,
    ratingsLevel: "/images/ratings.svg",
    completed: false,
  },
  {
    id: "lifestyle-task",
    score: 15,
    reward: 5,
    approximateTime: 8,
    bgColor: "bg-white",
    taskTitle: "Lifestyle Task",
    ratings: 675,
    ratingsLevel: "/images/ratings.svg",
    completed: false,
  },
  {
    id: "migration-task",
    score: 15,
    reward: 5,
    approximateTime: 8,
    bgColor: "bg-white",
    taskTitle: "Migration Task",
    ratings: 675,
    ratingsLevel: "/images/ratings.svg",
    completed: false,
  },
  {
    id: "home-task",
    score: 15,
    reward: 5,
    approximateTime: 8,
    bgColor: "bg-white",
    taskTitle: "Home Task",
    ratings: 675,
    ratingsLevel: "/images/ratings.svg",
    completed: false,
  },
];

export const surveys = [
  {
    id: "health-survey",
    score: 45,
    reward: 5,
    approximateTime: 5,
    bgColor: "bg-[#D8EBFF]",
    surveyTitle: "HEALTH SURVEYS",
    surveyDescription: "Complete 5 surveys and Earn more tokens",
    priority: false,
    completed: true,
  },
  {
    id: "health-survey",
    score: 45,
    reward: 5,
    approximateTime: 5,
    bgColor: "bg-[#D8EBFF]",
    surveyTitle: "HEALTH SURVEYS",
    surveyDescription: "Complete 5 surveys and Earn more tokens",
    priority: false,
    completed: true,
  },
];
